var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/apply/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0a5-hld._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0p4164o.js")
R.c("server/chunks/ssr/[root-of-the-server]__00se2u5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0nthen8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_@opentelemetry_api_index_0zv0b3p.js")
R.c("server/chunks/ssr/_buildcheck2_0c13l37._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_0dv6b02._.js")
R.c("server/chunks/ssr/_01gp9mf._.js")
R.c("server/chunks/ssr/node_modules_next_dist_06c_2qf._.js")
R.m(83841)
module.exports=R.m(83841).exports
