// data.jsx — scenario data for 한국 → 일본
const SCENARIO = {
  pet: {
    name: '엘리',
    nameEn: 'Ellie',
    species: 'Dog',
    breed: 'Goldendoodle',
    color: 'Yellow',
    sex: 'Spayed female',
    birthDate: '2022-03-07',
    age: '4Y 2M',
    weight: '22kg',
    microchip: '933 000 320 606 599',
    photo: 'ellie',
  },
  guardian: {
    name: '강경훈',
    nameEn: 'Gyeonghun Kang',
    relation: '보호자',
    phone: '010-6644-1142',
    email: 'khoon5276@gmail.com',
    addressKo: '경기 안성시 양성면 노곡길 50-51',
    addressEn: '50-51 Nogok-gil, Yangseong-myeon, Anseong-si, Gyeonggi-do, Republic of Korea',
    postalCode: '17500',
  },
  trip: {
    fromCity: '서울',
    fromCountry: '한국',
    toCity: '도쿄',
    toCountry: '일본',
    flagFrom: '🇰🇷',
    flagTo: '🇯🇵',
    departureDate: '2026-05-26',
    returnDate: '2026-08-26',
    tripType: 'roundtrip',
    daysLeft: 21,
  },
  flights: [
    {
      direction: 'outbound', label: '출국',
      airline: 'Japan Airlines', flightNo: 'JAL 954',
      from: 'ICN', fromCity: '인천', to: 'NRT', toCity: '나리타',
      date: '2026-05-26', depart: '10:25', arrive: '12:50',
      cabin: '화물칸 위탁', kennel: 'IATA 200',
    },
    {
      direction: 'inbound', label: '귀국',
      airline: 'Japan Airlines', flightNo: 'JAL 957',
      from: 'NRT', fromCity: '나리타', to: 'ICN', toCity: '인천',
      date: '2026-08-26', depart: '14:10', arrive: '16:55',
      cabin: '화물칸 위탁', kennel: 'IATA 200',
    },
  ],
  clinic: {
    name: '연남동 동물의료센터',
    address: '서울 마포구 연남로 12',
    phone: '02-•••-3340',
    role: '검역 · 채혈 담당',
  },
  transport: {
    name: 'PetMove Logistics',
    contact: '오정훈 매니저',
    phone: '02-•••-2030',
    role: '공항 픽업 · 화물 위탁',
  },
  vet: {
    name: '오정훈 수의사',
    title: 'PetMove 대표 / 수석 수의사',
    license: '농림부 면허 12047',
    years: 20,
    phone: '02-•••-2030',
    avatarTone: 'sage',
    initials: 'OJ',
  },
  // Timeline — 8 stages, current step is 4 (항체가 검사)
  stages: [
    { id: 's1', label: '의뢰 접수',       short: '접수',     date: '2026-04-18', state: 'done',     desc: '상담 완료, 견적 확정' },
    { id: 's2', label: '마이크로칩 확인',  short: '칩 확인',   date: '2026-04-22', state: 'done',     desc: 'ISO 11784 규격 확인' },
    { id: 's3', label: '광견병 백신 접종', short: '백신',     date: '2026-04-29', state: 'done',     desc: '3차 접종 / 항체 형성 대기' },
    { id: 's4', label: '광견병항체가 검사',       short: '항체 검사', date: '2026-05-12', state: 'current', desc: '채혈 → 일본 지정 검사기관 송부', sub: 'D-7 · 다음 단계' },
    { id: 's5', label: '검역 신청',        short: '신청',     date: '2026-05-19', state: 'upcoming', desc: '농림축산검역본부 사전신고' },
    { id: 's6', label: '검역증 발급',      short: '증명서',    date: '2026-05-23', state: 'upcoming', desc: '출국 7일 이내 발급' },
    { id: 's7', label: '항공 예약 확정',   short: '항공',     date: '2026-05-25', state: 'upcoming', desc: 'JAL 954 / 화물칸 예약' },
    { id: 's8', label: '출국 · 도착',      short: '출국',     date: '2026-05-26', state: 'upcoming', desc: '나리타 도착 → 동물검역소' },
  ],
  documents: [
    { id: 'd1', name: '예방접종 증명서',     date: '2026-04-29', size: '342 KB', type: 'pdf', source: '병원 발급', verified: true },
    { id: 'd2', name: '마이크로칩 등록증',   date: '2026-04-22', size: '128 KB', type: 'pdf', source: '병원 발급', verified: true },
    { id: 'd3', name: '광견병 항체가 검사 의뢰서', date: '2026-05-12', size: '210 KB', type: 'pdf', source: 'PetMove', verified: true, fresh: true },
    { id: 'd4', name: '여권 사본',           date: '2026-04-18', size: '1.2 MB', type: 'jpg', source: '고객 업로드', verified: true },
    { id: 'd5', name: '항체가 검사 결과지',  date: null,         size: null,    type: 'pdf', source: '대기 중', verified: false, pending: true },
    { id: 'd6', name: '동물검역증명서',     date: null,         size: null,    type: 'pdf', source: '발급 예정', verified: false, pending: true },
  ],
  messages: [
    { from: 'vet',  time: '오늘 09:14', text: '엘리 항체가 검사 의뢰서 업로드해 두었어요. 5월 12일 오전 10시에 병원에서 채혈 진행하면 됩니다 🐾' },
    { from: 'me',   time: '오늘 09:21', text: '네 알겠습니다. 그날 다른 음식 주의사항 있을까요?' },
    { from: 'vet',  time: '오늘 09:24', text: '채혈 4시간 전부터는 금식 부탁드립니다. 물은 괜찮아요.' },
    { from: 'system', time: '오늘 09:24', text: "다음 단계 '항체가 검사' D-7" },
  ],
};

window.SCENARIO = SCENARIO;
