var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0.zquoa._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0l-v8l~.js")
R.c("server/chunks/ssr/[root-of-the-server]__00se2u5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0nthen8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_@opentelemetry_api_index_0zv0b3p.js")
R.c("server/chunks/ssr/_buildcheck2_0c13l37._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/_buildcheck2__next-internal_server_app__not-found_page_actions_0asr5j_.js")
R.m(95169)
module.exports=R.m(95169).exports
